// Marcas compartidas para selectores de vehículo (perfil, comercio, etc.).
// Misma lista que la portada para mantener consistencia visual.

export const CAR_BRANDS = [
  { name: 'Audi', icon: '/catalog-assets/car-brands/audi.png' },
  { name: 'BMW', icon: '/catalog-assets/car-brands/bmw.png' },
  { name: 'Chevrolet', icon: '/mobile-catalog/brands/chevrolet.png' },
  { name: 'Chevy', icon: '/catalog-assets/car-brands/chevy.png' },
  { name: 'Daihatsu', icon: '/mobile-catalog/brands/Daihatsu.png' },
  { name: 'Daewoo', icon: '/catalog-assets/car-brands/daewoo.png' },
  { name: 'Dodge', icon: '/catalog-assets/car-brands/dodge.png' },
  { name: 'Dongfeng', icon: '/catalog-assets/car-brands/dongfeng.png' },
  { name: 'Fiat', icon: '/catalog-assets/car-brands/fiat.png' },
  { name: 'Ford', icon: '/mobile-catalog/brands/ford.png' },
  { name: 'Honda', icon: '/catalog-assets/car-brands/honda.png' },
  { name: 'Hyundai', icon: '/mobile-catalog/brands/hyundai.png' },
  { name: 'Jeep', icon: '/catalog-assets/car-brands/jeep.png' },
  { name: 'Kia', icon: '/catalog-assets/car-brands/kia.png' },
  { name: 'Mazda', icon: '/mobile-catalog/brands/mazda.png' },
  { name: 'Mercedes-Benz', icon: '/catalog-assets/car-brands/mercedesbenz.png' },
  { name: 'Mitsubishi', icon: '/mobile-catalog/brands/mitsubishi.png' },
  { name: 'Nissan', icon: '/catalog-assets/car-brands/nissan.png' },
  { name: 'Peugeot', icon: '/catalog-assets/car-brands/peugeot.png' },
  { name: 'Renault', icon: '/mobile-catalog/brands/renault.png' },
  { name: 'Subaru', icon: '/catalog-assets/car-brands/subaru.png' },
  { name: 'Suzuki', icon: '/mobile-catalog/brands/suzuki.png' },
  { name: 'Toyota', icon: '/mobile-catalog/brands/toyota.png' },
  { name: 'Volkswagen', icon: '/mobile-catalog/brands/volkswagen.png' },
]

export const MOTO_BRANDS = [
  { name: 'AVA', icon: '/catalog-assets/moto-brands/ava.png' },
  { name: 'Bajaj', icon: '/catalog-assets/moto-brands/bajaj.png' },
  { name: 'Bera', icon: '/catalog-assets/moto-brands/bera.png' },
  { name: 'CFMoto', icon: '/catalog-assets/moto-brands/cfmoto.png' },
  { name: 'Ducati', icon: '/catalog-assets/moto-brands/ducati.png' },
  { name: 'Empire', icon: '/catalog-assets/moto-brands/empire.png' },
  { name: 'Forza', icon: '/catalog-assets/moto-brands/forza.png' },
  { name: 'Haojue', icon: '/catalog-assets/moto-brands/haojue.png' },
  { name: 'Harley-Davidson', icon: '/catalog-assets/moto-brands/harley-davidson.png' },
  { name: 'Honda', icon: '/catalog-assets/moto-brands/honda.png' },
  { name: 'Kawasaki', icon: '/catalog-assets/moto-brands/kawasaki.png' },
  { name: 'Keeway', icon: '/catalog-assets/moto-brands/keeway.png' },
  { name: 'KTM', icon: '/catalog-assets/moto-brands/ktm.png' },
  { name: 'Kymco', icon: '/catalog-assets/moto-brands/kymco.png' },
  { name: 'Loncin', icon: '/catalog-assets/moto-brands/loncin.png' },
  { name: 'Skygo', icon: '/catalog-assets/moto-brands/skygo.png' },
  { name: 'Suzuki', icon: '/catalog-assets/moto-brands/suzuki.png' },
  { name: 'UM', icon: '/catalog-assets/moto-brands/um.png' },
  { name: 'Vespa', icon: '/catalog-assets/moto-brands/vespa.png' },
  { name: 'Yamaha', icon: '/catalog-assets/moto-brands/yamaha.png' },
]
